# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_num',
            field=models.IntegerField(blank=True, verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True, verbose_name='Год'),
        ),
    ]
