# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20170425_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Издательство'),
        ),
    ]
